language: php

sudo: false

php:
  - 7
  - 7.1
  - 7.2
  - nightly

env: TMPDIR=/tmp USE_XDEBUG=false

branches:
  only:
    master

install:
  - phpenv rehash
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer phpstan

before_script:
  - if [[ "$USE_XDEBUG" == false ]]; then phpenv config-rm xdebug.ini || return 0; fi

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
